### ISSUE TITLE
cannot install on raspi Stretch 

### ISSUE THREAD

**Issue by erich74** [empierre/MyDomoAtHome#153]
If have the following message when trying to install:

sudo apt-get install MyDomoAtHome
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
Note : sélection de « mydomoathome » au lieu de « MyDomoAtHome »
Les NOUVEAUX paquets suivants seront installés :
  mydomoathome
0 mis à jour, 1 nouvellement installés, 0 à enlever et 0 non mis à jour.
Il est nécessaire de prendre 0 o/6 229 ko dans les archives.
Après cette opération, 35,7 Mo d'espace disque supplémentaires seront utilisés.
(Lecture de la base de données... 39190 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de .../mydomoathome_0.2.29_all.deb ...
npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead.
npm ERR! 
npm ERR! If you're sure you want to delete the entire cache, rerun this command with --force.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-10-21T16_15_17_298Z-debug.log
dpkg: erreur de traitement de l'archive /var/cache/apt/archives/mydomoathome_0.2.29_all.deb (--unpack) :
 le sous-processus nouveau script pre-installation a retourné une erreur de sortie d'état 1
Des erreurs ont été rencontrées pendant l'exécution :
 /var/cache/apt/archives/mydomoathome_0.2.29_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

thanks for your help!

**Comment by empierre** [comment]
Hello,

  You have npm 5, looks like it is different, can you try

Npm cqche verify

  And relaunch the npm install


Le 21 oct. 2017 18:25, "erich74" <notifications@github.com> a écrit :

If have the following message when trying to install:

sudo apt-get install MyDomoAtHome
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances
Lecture des informations d'état... Fait
Note : sélection de « mydomoathome » au lieu de « MyDomoAtHome »
Les NOUVEAUX paquets suivants seront installés :
mydomoathome
0 mis à jour, 1 nouvellement installés, 0 à enlever et 0 non mis à jour.
Il est nécessaire de prendre 0 o/6 229 ko dans les archives.
Après cette opération, 35,7 Mo d'espace disque supplémentaires seront
utilisés.
(Lecture de la base de données... 39190 fichiers et répertoires déjà
installés.)
Préparation du dépaquetage de .../mydomoathome_0.2.29_all.deb ...
npm ERR! As of npm@5, the npm cache self-heals from corruption issues and
data extracted from the cache is guaranteed to be valid. If you want to
make sure everything is consistent, use 'npm cache verify' instead.
npm ERR!
npm ERR! If you're sure you want to delete the entire cache, rerun this
command with --force.

npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2017-10-21T16_15_17_298Z-debug.log
dpkg: erreur de traitement de l'archive
/var/cache/apt/archives/mydomoathome_0.2.29_all.deb
(--unpack) :
le sous-processus nouveau script pre-installation a retourné une erreur de
sortie d'état 1
Des erreurs ont été rencontrées pendant l'exécution :
/var/cache/apt/archives/mydomoathome_0.2.29_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

thanks for your help!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/empierre/MyDomoAtHome/issues/153>, or mute the thread

**Comment by erich74** [comment]
Thanks for helping.
Same error after the cache verify

Here is the cache verify output:

Cache verified and compressed (~/.npm/_cacache):
Content verified: 278 (10334801 bytes)
Content garbage-collected: 2 (18163 bytes)
Index entries: 419
Finished in 5.543s

**Comment by erich74** [comment]
and just in case:

npm -v
5.5.1
pi@domoticz:~ $ node -v
v8.7.0
pi@domoticz:~ $

**Comment by empierre** [comment]
Hugh not tested on this super recent version, are you on pi and which
distro are you on ?

Le 21 oct. 2017 18:37, "erich74" <notifications@github.com> a écrit :

and just in case:

npm -v
5.5.1
pi@domoticz:~ $ node -v
v8.7.0
pi@domoticz:~ $

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/empierre/MyDomoAtHome/issues/153#issuecomment-338415273>,
or mute the thread

**Comment by erich74** [comment]
yes PI 3

Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.1 (stretch)
Release:	9.1
Codename:	stretch

**Comment by empierre** [comment]
https://github.com/resin-io-projects/simple-server-node/pull/12/commits/ab68171326a2d009e2e35763040486eb4fb7e994

**Comment by empierre** [comment]
NPM 5.0 does break prior code, because existing NPM caches are no longer used and the cache commands have been rewritten. Users will have to re-download any cached package.
https://www.infoworld.com/article/3198746/javascript/npm-5-reworks-the-cache-for-speed-but-will-break-with-older-code.html

**Comment by erich74** [comment]
Thanks for the feedback. 
Can you please just give me a bit more directions on how solve the issue when running sudo apt-get install MyDomoAtHome ?
Sorry I'm not sure about the steps to perform.
Thanks

**Comment by empierre** [comment]
Hello, these are notes for me 😃

Had no time to set up env yet, did research on the issue

**Comment by erich74** [comment]
oops ok sorry :)
no worries, waiting for your feedback 
thanks

**Comment by empierre** [comment]
default stretch version: 4.8

apt-get install npm
ln -sf /usr/bin/nodejs /usr/bin/node

installation ok

**Comment by empierre** [comment]
@erich74 how did you install node 5 ? it is not in thee standard distro from etch ?

**Comment by empierre** [comment]
manual install:

curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
apt install nodejs

works fine

**Comment by empierre** [comment]
Node.js v5.x is no longer actively supported!
   * https://deb.nodesource.com/setup_4.x — Node.js v4 LTS "Argon" (recommended)
   * https://deb.nodesource.com/setup_6.x — Node.js v6 Current

**Comment by erich74** [comment]
will check again but I guess this was part of the install procedure for homebridge

**Comment by erich74** [comment]
I'm a bit lost, when I installed homebridge I followedd the instructions here: https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

node -v = v8.7.0

are you talking about node or npm version (5.5.1 on my pi)?

**Comment by empierre** [comment]
manual install:

curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
apt install nodejs

issue reproduced but this is a npm issue I'm looking in with impact on all previous versions

**Comment by erich74** [comment]
yes this is the install command I used: 

curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs

**Comment by empierre** [comment]
ok found a workaround, testing it

**Comment by empierre** [comment]
ok works, releasing version

**Comment by erich74** [comment]
great! I'll test it and let you know.
Thanks a lot for the update!
