### ISSUE TITLE
Switch Type Contact

### ISSUE THREAD

**Issue by houk001** [empierre/MyDomoAtHome#89]
Hello
Switch type Contact commonly used for door or windows sensor in Imperihome is recognized as switch widget like light bulbs, there is no way to add in imperi composite security widget and add to it window or door sensor. It works only with switch type door lock.

**Comment by empierre** [comment]
Hello,

  I already had this discussion, the issue is to find this is a DevDoor or DevLock from Domoticz.

  What have you for those device in Domoticz from:
/json.htm?type=devices&filter=all&used=true&order=Name

  If you edit the switch in domoticz and move it to "SwitchType" : "Door Lock" then you will find it as a DevDoor in Imperihome. 

  For Contact, it cannot easily be used outise of specific hardware use. You cannot change the icon on it and so on... The only thing I could do is change Contact switched to DevDoor systématically but that may impact other people using it for something else.

  what do you think ?

**Comment by houk001** [comment]
My problem is adding 9 window sensors. Currently i added this sensors as on/off with window picture but this is action device, not sensor only. 

How to change in code for myself type contact to type devdoor?

**Comment by empierre** [comment]
I can try to chage it tonight and push it, making DZ contact device seen as DevDoor in Imperihome, will see if others have an issue on that

**Comment by houk001** [comment]
OK Thank you

**Comment by empierre** [comment]
ok version 0.1.15 to be tested

**Comment by houk001** [comment]
Its working, Thank You again.

**Comment by houk001** [comment]
After upgrade from 0.13 to 0.1.15 graph for temp stop working and camera is not available in switches.
Maybe i do something wrong because ver 0.13 i have installed from git clone repository and this new is from deb package and i have error at the first time

pm ERR! Error: EACCES: permission denied, mkdir '/home/domo/.npm/basic-auth'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, mkdir '/home/domo/.npm/basic-auth']

second time its work with warn only 
Setting up mydomoathome (0.1.15) ...
npm WARN optional dep failed, continuing fsevents@1.0.11
basic-auth@1.0.3 node_modules/basic-auth

And when i stop the daemon the processes is still running. 
Ubuntu 14.04 here...

**Comment by empierre** [comment]
you were running the old old perl version:
- camera removed for it made more issues than it solved... so far (and unless people insist) I've not planned to have it back for imperihome supports direct camera inclusion
- graphes..I'm rewriting it right now ;-)

the error you have shouild not happen, try:

chmod -R a+w /home/domo/.npm

**Comment by houk001** [comment]
Direct camera is good if you in internal network.
What for external network? Currently i'm using for camera micasa vera but my plan is to switch to domoticz and sold vera.

**Comment by empierre** [comment]
ok added as 
https://github.com/empierre/MyDomoAtHome/issues/91
